name: fullstack-ci-cd
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./api
        run: yarn install --frozen-lockfile

      - name: Integration test
        working-directory: ./api
        run: yarn test

      - name: Build
        working-directory: ./api
        run: yarn run build

      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          cd /home/ubuntu/app/fullstack-example
          git pull origin main
          cd /home/ubuntu/app/fullstack-example/api
          yarn install
          yarn start
